### ISSUE TITLE
Beautify Tiny Dancer

### ISSUE THREAD

**Issue by SmokinClove** [SmokinClove/moon-walker#11]
Make Tiny Dancer less squarish

**Comment by cSparkle** [comment]
I'd like to tackle this one, please! 😄

**Comment by SmokinClove** [comment]
Please go ahead, thank you! :D

**Comment by cSparkle** [comment]
I don't think I'll actually have time to get around to this 😢 I wanted to let you know so someone else can claim it. Good luck on your project!

**Comment by SmokinClove** [comment]
Don't worry :D appreciate the thought. Hope you have completed Hacktoberfest, there is still 1 more day to go! if i can be of help with that let me know ;)
