### ISSUE TITLE
Add something to the ceiling on top of the dance space

### ISSUE THREAD

**Issue by SmokinClove** [SmokinClove/moon-walker#14]
Could be a random inspirational quote

**Comment by rmasianjr** [comment]
Hi, i want to try it.. can i? :relaxed:
should the quote be static or get from an api? thanks..

**Comment by SmokinClove** [comment]
Hi please feel free to do so, i was hoping to have an api with a random quote every time if possible! Please reference this issue in the PR so i can avoid clashing in PRs :)

Would be best if you could add the quote inside the "ceiling" div.

Let me know if i could help to clarify further :D Thank you!
![image](https://user-images.githubusercontent.com/12591759/66811083-0ff49a00-ef63-11e9-9fcc-eb8bff458fcb.png)

**Comment by rmasianjr** [comment]
copy that..
question, what do you mean "every time if possible"? every time i start/open the app or every certain amount of time?.. thanks :)

**Comment by SmokinClove** [comment]
Oh i was thinking on every load is good enough :D but i leave it to you! Surprise me 😼

**Comment by rmasianjr** [comment]
Lol.. ok sir.. working on this now :) ..thanks
